<?php

use Illuminate\Database\Seeder;

class TolerancesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tolerances')->delete();
        
        \DB::table('tolerances')->insert(array (
            0 => 
            array (
                'id' => 12,
                'max_val' => '0.00',
                'min_val' => '-0.30',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'id' => 13,
                'max_val' => '0.15',
                'min_val' => '-0.15',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'id' => 14,
                'max_val' => '0.00',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'id' => 15,
                'max_val' => '0.25',
                'min_val' => '-0.25',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'id' => 16,
                'max_val' => '0.00',
                'min_val' => '-0.80',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'id' => 17,
                'max_val' => '0.40',
                'min_val' => '-0.40',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'id' => 18,
                'max_val' => '0.00',
                'min_val' => '-1.20',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 5,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'id' => 19,
                'max_val' => '0.60',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 5,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'id' => 20,
                'max_val' => '0.00',
                'min_val' => '-2.00',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 6,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'id' => 21,
                'max_val' => '1.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 1,
                'quality_id' => 6,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'id' => 22,
                'max_val' => '0.00',
                'min_val' => '-0.40',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'id' => 23,
                'max_val' => '0.20',
                'min_val' => '-0.20',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'id' => 24,
                'max_val' => '0.00',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'id' => 25,
                'max_val' => '0.30',
                'min_val' => '-0.30',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'id' => 26,
                'max_val' => '0.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'id' => 27,
                'max_val' => '0.50',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'id' => 28,
                'max_val' => '0.00',
                'min_val' => '-1.50',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 5,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'id' => 29,
                'max_val' => '0.75',
                'min_val' => '-0.75',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 5,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'id' => 30,
                'max_val' => '0.00',
                'min_val' => '-2.50',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 6,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'id' => 31,
                'max_val' => '1.25',
                'min_val' => '-1.25',
                'system' => 'shaft',
                'range_id' => 2,
                'quality_id' => 6,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'id' => 32,
                'max_val' => '0.00',
                'min_val' => '-0.40',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'id' => 33,
                'max_val' => '0.20',
                'min_val' => '-0.20',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            22 => 
            array (
                'id' => 34,
                'max_val' => '0.00',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            23 => 
            array (
                'id' => 35,
                'max_val' => '0.30',
                'min_val' => '-0.30',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'id' => 36,
                'max_val' => '0.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            25 => 
            array (
                'id' => 37,
                'max_val' => '0.50',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            26 => 
            array (
                'id' => 38,
                'max_val' => '0.00',
                'min_val' => '-1.50',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 5,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            27 => 
            array (
                'id' => 39,
                'max_val' => '0.75',
                'min_val' => '-0.75',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 5,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            28 => 
            array (
                'id' => 40,
                'max_val' => '0.00',
                'min_val' => '-2.50',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 6,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            29 => 
            array (
                'id' => 41,
                'max_val' => '1.25',
                'min_val' => '-1.25',
                'system' => 'shaft',
                'range_id' => 3,
                'quality_id' => 6,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            30 => 
            array (
                'id' => 42,
                'max_val' => '0.00',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            31 => 
            array (
                'id' => 43,
                'max_val' => '0.25',
                'min_val' => '-0.25',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            32 => 
            array (
                'id' => 44,
                'max_val' => '0.00',
                'min_val' => '-0.80',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            33 => 
            array (
                'id' => 45,
                'max_val' => '0.40',
                'min_val' => '-0.40',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            34 => 
            array (
                'id' => 46,
                'max_val' => '0.00',
                'min_val' => '-1.20',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            35 => 
            array (
                'id' => 47,
                'max_val' => '0.60',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            36 => 
            array (
                'id' => 48,
                'max_val' => '0.00',
                'min_val' => '-2.00',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 5,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            37 => 
            array (
                'id' => 49,
                'max_val' => '1.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 5,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            38 => 
            array (
                'id' => 50,
                'max_val' => '0.00',
                'min_val' => '-3.00',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 6,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            39 => 
            array (
                'id' => 51,
                'max_val' => '1.50',
                'min_val' => '-1.50',
                'system' => 'shaft',
                'range_id' => 4,
                'quality_id' => 6,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            40 => 
            array (
                'id' => 52,
                'max_val' => '0.00',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            41 => 
            array (
                'id' => 53,
                'max_val' => '0.25',
                'min_val' => '-0.25',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            42 => 
            array (
                'id' => 54,
                'max_val' => '0.00',
                'min_val' => '-0.80',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            43 => 
            array (
                'id' => 55,
                'max_val' => '0.40',
                'min_val' => '-0.40',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            44 => 
            array (
                'id' => 56,
                'max_val' => '0.00',
                'min_val' => '-1.20',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            45 => 
            array (
                'id' => 57,
                'max_val' => '0.60',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            46 => 
            array (
                'id' => 58,
                'max_val' => '0.00',
                'min_val' => '-2.00',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 5,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            47 => 
            array (
                'id' => 59,
                'max_val' => '1.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 5,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            48 => 
            array (
                'id' => 60,
                'max_val' => '0.00',
                'min_val' => '-3.00',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 6,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            49 => 
            array (
                'id' => 61,
                'max_val' => '1.50',
                'min_val' => '-1.50',
                'system' => 'shaft',
                'range_id' => 5,
                'quality_id' => 6,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            50 => 
            array (
                'id' => 62,
                'max_val' => '0.00',
                'min_val' => '-0.60',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 1,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            51 => 
            array (
                'id' => 63,
                'max_val' => '0.30',
                'min_val' => '-0.30',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 1,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            52 => 
            array (
                'id' => 64,
                'max_val' => '0.00',
                'min_val' => '-1.00',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 2,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            53 => 
            array (
                'id' => 65,
                'max_val' => '0.50',
                'min_val' => '-0.50',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 2,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            54 => 
            array (
                'id' => 66,
                'max_val' => '0.00',
                'min_val' => '-1.50',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 4,
                'field_id' => 8,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
            55 => 
            array (
                'id' => 67,
                'max_val' => '0.75',
                'min_val' => '-0.75',
                'system' => 'shaft',
                'range_id' => 6,
                'quality_id' => 4,
                'field_id' => 9,
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}
